name: Build Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  #AZURE_WEBAPP_NAME: devopsoh05189poi  # set this to the name of your Azure Web App
  RESOURCE_GROUP: Fenesys-Test
  #SLOT_NAME: staging
  ACR_IMAGES: testfenesys.azurecr.io/devopsoh/api-poi
  ACR_REGISTRY: TestFenesys
  #POI_STAGING_URL: https://devopsoh05189poi-staging.azurewebsites.net/api/version/poi

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Performing Checkout
    - name: Git Checkout
      uses: actions/checkout@v3
    # Setting Python version
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install fastapi
        pip install fastapi uvicorn
        pip install python-dotenv
        pip install aiohttp
        pip install azure-cosmos
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        #pip install -r requirements.txt
        #pip install pytest
        #pip install pytest-cov
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true
      
    - name: Install tox and any other packages
      run: pip install tox
      
    - name: Run Tox for testing
      run: tox -e py
      
    #- name: Test with pytest
      #run: |
        #pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    #- name: Run the application
      #run: |
        #cd cosmosdb-with-fastapi
        #uvicorn cosmosdb-with-fastapi.main:app --reload
    
    - name: Get repo name
      # actions/github-script@v6 is breaking change which is node16
      uses: actions/github-script@v5
      id: resources_prefix
      with:
          result-encoding: string
          script: return context.repo.repo.toLowerCase()
    # Usage for current job: ${{ steps.resources_prefix.outputs.result }}
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: ACR Build
      uses: azure/CLI@v1
      with:
        # azcliversion: 2.30.0
        inlineScript: |
          az extension add --name containerapp --upgrade
          az acr login --name ${{ env.ACR_REGISTRY }}
          az acr build \
           --build-arg build_version=${{ github.run_id }} \
           --registry ${{ env.ACR_REGISTRY }} \
           --resource-group ${{ env.RESOURCE_GROUP }} \
           --image ${{ env.ACR_IMAGES }}:{{ github.run_id }} .
           
    - name: ACR Image Checker
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az acr repository list --name ${{ env.ACR_REGISTRY }}
