name: Docker Build Image

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
   RESOURCE_GROUP: Fenesys-Test

defaults:
  run:
    working-directory: "cosmosdb-with-fastapi/*"

jobs:
    Docker-build-:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: testfenesys.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -f Dockerfile -t testfenesys.azurecr.io/fenesys:${{ github.sha }}
            docker push testfenesys.azurecr.io/fenesys:${{ github.sha }}
            
        #- name: 'Deploy to Azure Container Instances'
          #uses: 'azure/aci-deploy@v1'
          #with:
            #resource-group: ${{ env.RESOURCE_GROUP }}
            #dns-name-label: ${{ env.RESOURCE_GROUP }}${{ github.run_id }}
            #image: testfenesys.azurecr.io/fenesys::${{ github.sha }}
            #registry-login-server: testfenesys.azurecr.io
            #registry-username: ${{ secrets.REGISTRY_USERNAME }}
            #registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            #name: aci-sampleapp
            #location: 'west us'
        - name: Build and deploy Container App
          uses: azure/container-apps-deploy-action@v0
          with:
            appSourcePath: ${{ github.workspace }}
            resourceGroup: Fenesys-Test
            acrName: TestFenesys
            containerAppName: fenesystest
            imageToBuild: testfenesys.azurecr.io/fenesys:${{ github.sha }}
