name: Docker Image CI

on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    working-directory: "cosmosdb-with-fastapi/src"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tueone:$(date +%s)
    - name: Docker run
      run: docker run -p 8080:8080 -t tueone:$(date +%s)
